# Ultimate ML DL BootCamp- NumPy Assignment



#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__, np.__config__)

2.4.0 <module 'numpy.__config__' from '/home/light/Desktop/python-hw/env/lib/python3.13/site-packages/numpy/__config__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
import sys
a = np.arange(10)
sys.getsizeof(a)

192

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via the defau

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[5] = 1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
a = np.arange(1, 11)
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a = np.array([1,2,0,0,4,0])
np.where(a < 1)

(array([2, 3, 5]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random(27).reshape(3,3,3)

array([[[0.12320175, 0.17464699, 0.33543008],
        [0.99446377, 0.75199191, 0.618031  ],
        [0.56575461, 0.37203163, 0.23561581]],

       [[0.04497666, 0.87870608, 0.48025233],
        [0.94513225, 0.28913197, 0.74913818],
        [0.91490427, 0.8016326 , 0.3664191 ]],

       [[0.27698994, 0.17332348, 0.93714938],
        [0.61175626, 0.43166175, 0.32001976],
        [0.68760661, 0.50031529, 0.64495968]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.random(100).reshape(10,10)
max_val = np.max(a)
min_val = np.min(a)

print(f"""
            matrix = {a}
            Max value = {max_val}
            Min Value = {min_val}
        """)


            matrix = [[0.49856161 0.42148268 0.33570858 0.90094934 0.18213331 0.57860857
  0.30043113 0.78546219 0.88278275 0.44231017]
 [0.62181991 0.6217762  0.1892981  0.74135457 0.83384896 0.01151538
  0.01435248 0.45986714 0.07518434 0.6651116 ]
 [0.22539699 0.82110616 0.66499795 0.75174911 0.97092679 0.17967657
  0.22885585 0.9834081  0.14850275 0.59102349]
 [0.17284058 0.74284362 0.66083877 0.41402553 0.48997422 0.8474007
  0.99087606 0.55544881 0.40042517 0.42971285]
 [0.17701109 0.4658332  0.2134229  0.45212561 0.23678778 0.25397997
  0.27518108 0.56689519 0.01759455 0.88943705]
 [0.39180285 0.36719868 0.05205403 0.00180568 0.67396282 0.48872681
  0.87937909 0.84667591 0.80746716 0.74763861]
 [0.61774886 0.45803753 0.42306445 0.19133417 0.86028513 0.00991618
  0.19275196 0.06167763 0.33384338 0.50666324]
 [0.83716499 0.66882097 0.78882865 0.72764514 0.54520429 0.56752133
  0.71330516 0.58924101 0.72818021 0.30282065]
 [0.09310111 0.58029892 0.80102647 0.29280572 0.51557714 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.mean(np.random.random(30))

np.float64(0.5558655695598971)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
import numpy as np
a = np.ones(25).reshape(5,5)
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.arange(1,17).reshape(4,4)

rows, cols = a.shape
b = np.zeros((rows+2, cols+2))
b[1:-1, 1:-1] = a
b

# np.pad(a, 1, mode='constant', constant_values=0)


array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  0.],
       [ 0.,  5.,  6.,  7.,  8.,  0.],
       [ 0.,  9., 10., 11., 12.,  0.],
       [ 0., 13., 14., 15., 16.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(f""" 
           1. {0 * np.nan} is nan (anything multiplied to nan returns a nan)
           2. {np.nan == np.nan} is false (any comparison with nan is false)
           3. {np.inf > np.nan} is false same prev reason
           4. {np.nan - np.nan} any arithmatic returns nan same as 1
           5. {np.nan in set([np.nan])} returns true 
           6. {0.3 == 3 * 0.1} false because of floating point 
           """)

 
           1. nan is nan (anything multiplied to nan returns a nan)
           2. False is false (any comparison with nan is false)
           3. False is false same prev reason
           4. nan any arithmatic returns nan same as 1
           5. True returns true 
           6. False false because of floating point 
           


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
a = np.zeros(25).reshape(5,5)

# rows, cols = a.shape
# val = 1
# for i in range(rows):
#     for j in range(cols):
#         if i == (j + 1):
#             a[i][j] = val
#             val = val + 1 

np.fill_diagonal(a[1:, :-1], np.arange(1,5))

a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
import numpy as np


# a = np.zeros((8,8)) // slower than numpy
# for i in range(8):
#     for j in range(8):
#         if (i + j) % 2 == 0:
#             a[i][j] = 1

# np.indices((8,8)).sum(axis = 0) % 2 //uses larger memory

i = np.arange(8)[:, None]
j = np.arange(8)
((i+j) % 2 == 0).astype(int)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
a = np.arange(6*7*8).reshape(6,7,8)

target_index = 99
x_axis = target_index // 56
target_index = target_index % 56
y_axis = target_index // 8
z_axis = target_index % 8

print(x_axis, y_axis, z_axis)

np.unravel_index(99, a.shape)


1 5 3


(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
np.tile([[1,0],[0,1]],(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.rand(5,5)
b = (a - a.min()) / (a.max() - a.min())
b

array([[0.55844198, 0.18975342, 0.68475987, 0.1384281 , 0.81117965],
       [0.19211383, 0.01206913, 0.15319832, 0.76109825, 0.84728502],
       [0.56047916, 0.79589456, 0.71423706, 0.52024456, 1.        ],
       [0.55005504, 0.53003143, 0.54733039, 0.08168994, 0.58898306],
       [0.87740344, 0.        , 0.65787193, 0.39616947, 0.27886183]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a = np.random.randint(1,10,(5,3))
b = np.random.randint(1,10,(3,2))

np.dot(a,b)


array([[ 47, 120],
       [ 55,  63],
       [ 40,  75],
       [ 52, 111],
       [ 48,  60]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
a = np.random.randint(1,10,10)
a[(a > 3) & (a < 8)] *= -1
a

array([ 8, -6, -4, -6, -7, -5,  8,  1,  2, -7])

#### 26. What is the output of the following script? (★☆☆)
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1)) #starting point is -1 (built in method sum) 9 
from numpy import *
print(sum(range(5),-1)) #numpy sum takes axis from which side it will start summing 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.array([1,2,3,4,5,6])
print(f""" 
{Z**Z} element wise expo
{2 << Z >> 2} applying element by element
{Z < -Z} element wise comparison
{1j*Z} complex number
{Z/1/1} dividing by 1/1 which is 1 so just converting into float
""")
# {Z<Z>Z} ambigious

 
[    1     4    27   256  3125 46656] element wise expo
[ 1  2  4  8 16 32] applying element by element
[False False False False False False] element wise comparison
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j] complex number
[1. 2. 3. 4. 5. 6.] dividing by 1/1 which is 1 so just converting into float



#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
np.array(0) / np.array(0) #null value
np.array(0) // np.array(0) #zero division error
np.array([np.nan]).astype(int).astype(float) #nan can't be converted into any type

/tmp/ipykernel_196476/4161179653.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) #null value
/tmp/ipykernel_196476/4161179653.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) #zero division error
/tmp/ipykernel_196476/4161179653.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float) #nan can't be converted into any type


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
a = np.array([1.2,2.3,3.4,4.5,5.6])
np.rint(a).astype(int)

array([1, 2, 3, 4, 6])

#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
a = np.arange(1,20,2)
b = np.arange(1,20,4)
np.intersect1d(a,b)

array([ 1,  5,  9, 13, 17])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
np.seterr(all="ignore")
np.array([nan]).astype(int)
np.seterr(all='warn')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)
#emath from numpy complex math but sqrt can't handle -1 as it is for real numbers
# result = false

/tmp/ipykernel_196476/4117272494.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
import datetime as dt
today = dt.datetime.now()
prev = today - dt.timedelta(1)
tom = today + dt.timedelta(1)

print(f"""
Yesterday: {prev.strftime("%d, %m, %y")}
Today: {today.strftime("%d, %m, %y")}
Tomorrow: {tom.strftime("%d, %m, %y")}
""")


Yesterday: 25, 12, 25
Today: 26, 12, 25
Tomorrow: 27, 12, 25



#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
np.arange('2016-07','2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
a = np.arange(10)
b = np.arange(10,20)
b = np.add(a,b)
a = np.divide(-a, b)
np.multiply(a,b)

array([ 0., -1., -2., -3., -4., -5., -6., -7., -8., -9.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [43]:
arr = np.array([1.2, 3.9, 5.5, 0.7, 10.99])
m1 = arr.astype(int)
m2 = np.floor(arr).astype(int)
m3 = np.trunc(arr).astype(int)
m4 = np.ceil(arr).astype(int)
print(m1, m2, m3, m4)

[ 1  3  5  0 10] [ 1  3  5  0 10] [ 1  3  5  0 10] [ 2  4  6  1 11]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [46]:
np.zeros((5,5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [50]:
def gen_ten_int():
    return [i for i in range(10)]

np.array(gen_ten_int())

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [77]:
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [90]:
np.sort(np.random.rand(10))

array([0.07894487, 0.14342753, 0.20393445, 0.31502872, 0.34489211,
       0.5044801 , 0.52266416, 0.56335922, 0.66715337, 0.90851558])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = np.arange(10)
arr.sum() #object sum or python sum is faster than np.sum()

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [421]:
arr1 = np.random.randint(1, 10, 10)
arr2 = np.random.randint(1, 10, 10)
np.array_equal(arr1, arr2)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [426]:
arr = np.arange(1, 10)
arr.flags.writeable = False
arr[1] = 3

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [430]:
cart = np.random.random((10,2))
x, y = cart[:,0], cart[:,1]
r = np.sqrt((np.square(x) + np.square(y)))
theta = np.arctan2(y,x)
np.column_stack((r,theta))

array([[0.74163849, 0.28609173],
       [1.05886695, 0.96113405],
       [1.31780756, 0.75759399],
       [0.57680023, 0.34499733],
       [0.23417971, 0.37391656],
       [0.47909915, 1.16369539],
       [0.75720696, 0.45264706],
       [0.28736531, 1.27009827],
       [0.53820176, 1.52065972],
       [0.34193565, 1.41516269]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [478]:
a = np.random.randint(1,10,10)
a[a.argmax()] = 0
a

array([4, 6, 7, 1, 5, 0, 1, 3, 1, 8])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
x = np.linspace(0,1, 5)
y = np.linspace(0,1, 5)
a, b = np.meshgrid(x, y)
structure = np.zeros((5,5), dtype=[('x','float64'), ('y', 'float64')])
structure['x'] = a
structure['y'] = b
structure

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [523]:
x = np.linspace(1, 5, 5)
y = np.linspace(6, 10, 5)
a, b = np.meshgrid(x,y, indexing='ij')
np.divide(1.0, np.subtract(a,b))

array([[-0.2       , -0.16666667, -0.14285714, -0.125     , -0.11111111],
       [-0.25      , -0.2       , -0.16666667, -0.14285714, -0.125     ],
       [-0.33333333, -0.25      , -0.2       , -0.16666667, -0.14285714],
       [-0.5       , -0.33333333, -0.25      , -0.2       , -0.16666667],
       [-1.        , -0.5       , -0.33333333, -0.25      , -0.2       ]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [537]:
dtypes = [
    np.int8, np.int16, np.int32, np.int64,
    np.uint8, np.uint16, np.uint32, np.uint64,
    np.float16, np.float32, np.float64
]
for dtype in dtypes:
    if np.issubdtype(dtype, np.integer):
        print(dtype.__name__, " Min: => ", np.iinfo(dtype).min, "Max: ==>", np.iinfo(dtype).max)
    else:
        print(dtype.__name__, " Min: => ", np.finfo(dtype).min, "Max: ==>", np.finfo(dtype).max)

int8  Min: =>  -128 Max: ==> 127
int16  Min: =>  -32768 Max: ==> 32767
int32  Min: =>  -2147483648 Max: ==> 2147483647
int64  Min: =>  -9223372036854775808 Max: ==> 9223372036854775807
uint8  Min: =>  0 Max: ==> 255
uint16  Min: =>  0 Max: ==> 65535
uint32  Min: =>  0 Max: ==> 4294967295
uint64  Min: =>  0 Max: ==> 18446744073709551615
float16  Min: =>  -6.55e+04 Max: ==> 6.55e+04
float32  Min: =>  -3.4028235e+38 Max: ==> 3.4028235e+38
float64  Min: =>  -1.7976931348623157e+308 Max: ==> 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [545]:
a = np.arange(1,200)
for x in a:
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [571]:
a = 5
ar = np.random.randint(1,10, 10)
index = np.abs(ar - a).argmin()
ar[index]

np.int64(5)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [586]:
dt = np.dtype([
    ('position', [('x','float64'), ('y', 'float64')]),
    ('color', [('r', 'uint8'), ('g', 'uint8'), ('b', uint8)])
])

ar = np.zeros(1, dtype=dt)
ar['position'][0] = (12,23)
ar['color'][0] = (255,0,0)
bd = np.array([((1,2), (255,23,233))],dtype=dt)
print(ar, bd, sep="\n")

[((12., 23.), (255, 0, 0))]
[((1., 2.), (255, 23, 233))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [782]:
vect = np.random.randint(1,101, 200).reshape(100,2)
dif = vect[:, np.newaxis, :] - vect[np.newaxis, :, :]
dist_mat = np.sqrt(np.sum(dif**2, axis=2))
# np.count_nonzero(dist_mat)-(100*100)
print(dist_mat)

[[ 0.         60.20797289 65.73431372 ... 62.29767251 73.24616031
  81.21576202]
 [60.20797289  0.          5.83095189 ...  8.         46.84015371
  81.54140053]
 [65.73431372  5.83095189  0.         ...  7.07106781 45.69463864
  82.00609733]
 ...
 [62.29767251  8.          7.07106781 ...  0.         39.2173431
  75.        ]
 [73.24616031 46.84015371 45.69463864 ... 39.2173431   0.
  39.40812099]
 [81.21576202 81.54140053 82.00609733 ... 75.         39.40812099
   0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [799]:
ar = np.array([1.2,2.3,3.4,4.5,5.6,6.7,7.8], dtype=float32)
ar.astype(np.int32)

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [808]:
from io import StringIO 
val = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11""" 

data = np.genfromtxt(StringIO(val), delimiter=',')
data[~np.isnan(data)].astype(int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [817]:
#close to enumerate in numpy is np.ndenumerate the difference is enumerate works with 1d but ndenumerate with multidimension
arr = np.random.randint(1,10, 8).reshape(4,2)
print(arr)
for x, y in np.ndenumerate(arr):
    print(f"Idx: {x} => Val = {y}")

[[3 5]
 [4 8]
 [3 5]
 [1 7]]
Idx: (0, 0) => Val = 3
Idx: (0, 1) => Val = 5
Idx: (1, 0) => Val = 4
Idx: (1, 1) => Val = 8
Idx: (2, 0) => Val = 3
Idx: (2, 1) => Val = 5
Idx: (3, 0) => Val = 1
Idx: (3, 1) => Val = 7


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)